title: "stanfor_products_dataset"
backbone:
    name: "iresnet50_normalized"
    learnable: false

scale_predictor:
    name: "MLPHead"
    num_feats: [25088, 512, 1]
    batch_norm: true
    activation: "exp"
    fp16: true

is_distributed: true
#network: "r50"
resume: true
source: "~"
loss: "arcface_scale"

#scale_source: "/gpfs/data/gpfs0/k.fedyanin/space/models/scale/02_sigm_mul_selection/32/checkpoint.pth"
scale_source: null
#output: "/beegfs/home/r.kail/faces/test"
output: "/gpfs/data/gpfs0/k.fedyanin/space/models/scale/08_online_products"
embedding_size: 512
sample_rate: 1.0
fp16: true
momentum: 0.9
#weight_decay: 5e-4
weight_decay: 0.0005
batch_size: 128
lr: 0.0001  # batch size is 512
scale_lr: 0.0001
freeze_backbone: true
#scale_predictor_sizes: [25088, 512, 1]
#scale_batch_norm: true
#scale_exponent: "exp"

dataset: "products"
rec: "/trinity/home/r.kail/faces/data/Stanford_Online_Products"
num_classes: 22634
num_image: 120,053
num_epoch: 12
warmup_epoch: -1
decay_epoch: [3, 6, 9]
val_targets: ["lfw", "cfp_fp", "agedb_30"]

